### ISSUE TITLE
webdriver-manager start error

### ISSUE THREAD

**Issue by Gennady77** [pose/webdriver-manager#20]
When I input command webdriver-manager start I get next:

E/config - nothing to return for a config file

assert.js:90
  throw new assert.AssertionError({
  ^
 AssertionError: missing path
    at Module.require (module.js:351:3)
    at require (internal/module.js:12:17)
    at Function.Config.binaryVersions (C:\Users.....\AppData\Roaming\npm\node_modules\webdriver-manager\built\lib\config.js:82:26)
    at C:\Users.....\AppData\Roaming\npm\node_modules\webdriver-manager\built\lib\binaries\chrome_driver.js:47:51
    at Object.<anonymous> (C:\Users....\AppData\Roaming\npm\node_modules\webdriver-manager\built\lib\binaries\chrome_driver.js:51:2)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

webdriver-manager 10.0.2, windows 10, npm 2.15.1

**Comment by pose** [comment]
Hi @Gennady77,

For `webdriver-manager>=10.0` please do check https://github.com/angular/webdriver-manager. Your issue seems to be already reported: https://github.com/angular/webdriver-manager/issues/39

Thanks in advance,
